// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmiyJM8DqCtDl4yYnoZmKkVJtZ9qpcnKs',
    appId: '1:256213987810:web:7307f1033eefb0f09409bb',
    messagingSenderId: '256213987810',
    projectId: 'mandaaquela-5601c',
    authDomain: 'mandaaquela-5601c.firebaseapp.com',
    storageBucket: 'mandaaquela-5601c.appspot.com',
    measurementId: 'G-S2Q2J067HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9nceRTv1zFLw7gBfFRL0_LbPf6wYSLrI',
    appId: '1:256213987810:android:5f5b041ef0a009689409bb',
    messagingSenderId: '256213987810',
    projectId: 'mandaaquela-5601c',
    storageBucket: 'mandaaquela-5601c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKp9NlT2OHWEnD7hF71tltFxxcMS7Dc4',
    appId: '1:256213987810:ios:33140164c8b668959409bb',
    messagingSenderId: '256213987810',
    projectId: 'mandaaquela-5601c',
    storageBucket: 'mandaaquela-5601c.appspot.com',
    iosClientId: '256213987810-4o9t850j8hbm6cptglvc6v5gnbp7r6u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandaAquela',
  );
}
